initial commit
paseaf/ContainerSSH-honeypot pull request #26
Opened 2022-06-23 22:38 UTC by bafread

## Description
> What changes will the PR bring? Refer to relevant issues if applicable
- Issue #25 
- [ v ] add all VMs to Monitoring
- [  ] add running Containers to Monitoring: (containerssh, containerssh-test-authconfig, and minio)
- [  ] visualize the Metrics using Grafana or ELK 

This PR will
- close #25
- Run node_exporter as Service -> if Server down and then the monitoring is up to date

## Testing the PR
> How do your team test if the PR is valid?
-  After building image with Packer and apply using Terraform, on <logger-vm>:9091, we can monitor all VMs (look Screenshot). 
  
## Takeaways
> What have you learned from the PR and want to share with your team?\
- Found an issue with Packer Build -> disconnect and stuff.
- Stuck at Instance Creation
- Building the project with Windows is unstable (at least for me, after Bluescreen) :(
- Successfully using git :)
  
## Q&A
> Your open questions to answer before merging the PR
- There is an issue with adding the docker's container to monitor -> will try to fix it on the next commit

![Screenshot from 2022-06-23 21-13-09](https://user-images.githubusercontent.com/106653277/175426165-a27e5fe9-7cec-45d4-bb83-8bdc97c2377c.png)

2022-06-23 22:40 UTC, bafread commented on packer/main.pkr.hcl
>    provisioner "shell" {
Move download_node_exporter to packer while building image.
If done on TF -> Issue: no connection from github server.

2022-06-23 22:41 UTC, bafread commented on packer/main.pkr.hcl
> +      "./scripts/create_node_exporter_service.sh",
Move download_node_exporter to packer while building image.
If done on TF -> Issue: no connection from github server.

2022-06-23 22:41 UTC, bafread commented on packer/main.pkr.hcl
> +    expect_disconnect = true
fix some disconnection issue

2022-06-23 22:41 UTC, bafread commented on packer/main.pkr.hcl
> +      "./scripts/create_node_exporter_service.sh",
Move download_node_exporter to packer while building image.
If done on TF -> Issue: no connection from github server.

2022-06-28 18:02 UTC, paseaf requested changes
looks great! :rocket: 
added some questions and suggestions.

2022-06-29 15:22 UTC, paseaf approved these changes
LGTM! added one more question but we could do it in future PRs!

2022-06-29 15:24 UTC, bafread commented on terraform/scripts/run_cadvisor.sh
> +VERSION=v0.39.3 # use the latest release version from https://github.com/google/cadvisor/releases
implemented on the current version, thanks for the suggestion :)

2022-06-29 15:36 UTC, paseaf commented on terraform/variables.tf
> +  default     = "gcp.key.json"
maybe it's `git add`ed before we have gitignore? Not sure :)
This might help
https://stackoverflow.com/a/19757964/11554998

2022-06-29 15:39 UTC, bafread commented on terraform/variables.tf
> +  default     = "gcp.key.json"
no this one is outdated

2022-06-29 16:22 UTC, merged